### ISSUE TITLE
Cannot access VPN files once new download option is selected 

### ISSUE THREAD

**Issue by T3arD0wn** [jonathandata1/Goliad#4]
When new vpn files are downloaded, the directory from where the processing takes place is `Goliad/CONNECTIONS`.
Once the files are completely downloaded, and then vpn connection is tried to be established, the files are not found as the `option1` tries to locate files inside `Goliad/CONNECTIONS/CONNECTIONS` as stated by code `ls -d -1 $PWD/CONNECTIONS/* ` in this case it becomes `ls -d -1 Goliad/CONNECTIONS/CONNECTIONS` which in turn fails since the files are present in  `Goliad/CONNECTIONS/`

For this a small PR has been raised.
https://github.com/jonathandata1/Goliad/pull/3

**Comment by jonathandata1** [comment]
awesome thank you for raising the issue I have approve the pull request
